export const BASE_URL = ''
export const USERS_URL = '/api/users'
export const CATEGORIES_URL = '/api/category'
export const UPLOADS_URL = '/api/upload'
export const PRODUCTS_URL = '/api/product'
export const ORDERS_URL= '/api/order'
export const PAYPAL_URL = '/api/config/paypal'